-- AMAZON SALES REPORRT (CLEANING AND ANALYZING DATA USING SQL)
SELECT * FROM amazon_sales_report;


-- CHECKING IF THERE ANY NULLS REMAINING IN THIS TABLE
SELECT COUNT(*) FROM amazon_sales_report WHERE SHIP_CITY IS NULL;
SELECT COUNT(*) FROM amazon_sales_report WHERE  ship_country IS NULL;
SELECT COUNT(*) FROM amazon_sales_report WHERE ship_postal_code IS NULL;
SELECT COUNT(*) FROM amazon_sales_report WHERE ship_state IS NULL;

-- QUERIES FOR DATA ANALYSIS
-- BASIC UNDERSTANDING THE DATA
SELECT COUNT(*) FROM amazon_sales_report;
SELECT * FROM amazon_sales_report WHERE ROWNUM <=10;
SELECT DISTINCT STATUS FROM amazon_sales_report;

-- DATA CLEANING QUERIES
UPDATE AMAZON_SALES_REPORT SET COURIER_STATUS = 'cancelled' WHERE COURIER_STATUS IS NULL;
UPDATE AMAZON_SALES_REPORT SET AMOUNT = 0 WHERE AMOUNT IS NULL;
UPDATE amazon_sales_report SET CURRENCY = 'INR' WHERE CURRENCY IS NULL;

-- IDENTIFY DUPLICATE ORDERS
SELECT ORDER_ID, COUNT(*) FROM AMAZON_SALES_REPORT
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

-- DELETE DUPLICATE VALUES
DELETE FROM
amazon_sales_report A WHERE ROWID > (
SELECT MIN(ROWID) FROM amazon_sales_report B 
WHERE A.ORDER_ID = B.ORDER_ID);

-- EXPLORATORY DATA ANALYSIS 

-- TOTAL ORDERS
SELECT COUNT(*) AS TOTAL_ORDERS FROM amazon_sales_report;

-- TOTAL REVENUE
SELECT SUM(AMOUNT)AS TOTAL_REVENUE FROM amazon_sales_report;

--TOTAL QUANTITY SOLD
SELECT (QTY)AS QUANTITY FROM amazon_sales_report;
SELECT SUM(QTY) AS TOTAL_QUANTITY FROM amazon_sales_report;

--NUMBER OF UNIQUE SKU'S
SELECT COUNT(*) AS TOTAL_SKU FROM amazon_sales_report;
SELECT COUNT(DISTINCT SKU) AS UNIQUE_SKU FROM amazon_sales_report;

--NUMBER OF UNIQUE CATEGORY, SIZE
SELECT COUNT(DISTINCT CATEGOR)AS UNIQUE_CATEGORY FROM amazon_sales_report;
SELECT COUNT(DISTINCT SIZE_) AS SIZES FROM amazon_sales_report;

--ORDERS BY STATUS
SELECT STATUS, COUNT(*)AS TOTAL_ORDERS FROM amazon_sales_report
GROUP BY STATUS
ORDER BY STATUS DESC;

--REVENUE BY CATEGORY
SELECT CATEGOR,SUM(AMOUNT)AS TOTAL_REVENUE FROM amazon_sales_report
GROUP BY CATEGOR
ORDER BY CATEGOR DESC;

--REVENUE B2B( TRUE VS FALSE)
SELECT B2B, SUM(AMOUNT) AS REV FROM amazon_sales_report
GROUP BY B2B
ORDER BY B2B DESC;

-- ORDERS PER DATE
SELECT ORDER_DATE, COUNT(ORDER_DATE)AS NO_OF_ORDERS FROM amazon_sales_report GROUP BY ORDER_DATE;

-- HIGHEST AND LEAST ORDERS BY DATE
SELECT ORDER_DATE, HIGHEST_ORDERS
FROM(SELECT ORDER_DATE, COUNT(*) AS HIGHEST_ORDERS FROM amazon_sales_report
GROUP BY ORDER_DATE
ORDER BY HIGHEST_ORDERS DESC)
WHERE ROWNUM = 1;

SELECT ORDER_DATE, LEAST_ORDERS
FROM( SELECT ORDER_DATE, COUNT(*) AS LEAST_ORDERS FROM amazon_sales_report
GROUP BY ORDER_DATE
ORDER BY LEAST_ORDERS)
WHERE ROWNUM = 1;

--TOP SELLING SKU'S BY QUANTITY
SELECT SKU,SUM(QTY)AS QUANTITY FROM amazon_sales_report
GROUP BY SKU
ORDER BY QUANTITY DESC;

-- AVERAGE ORDERS PER DAY
SELECT AVG(COUNT(ORDER_DATE)) AS TOTAL_ORDERS FROM amazon_sales_report
GROUP BY ORDER_DATE;

--AVERAGE REVENUE PER DAY
SELECT AVG(AMOUNT)AS AVG_REVENUE FROM amazon_sales_report;

--DAILY SALES TREND
SELECT ORDER_DATE, SUM(AMOUNT)AS INCOME_PER_DAY
FROM amazon_sales_report
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

--AVG AMOUNT PER DAY
SELECT ORDER_DATE,AVG(AMOUNT) FROM amazon_sales_report
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

--MONTHLY SALES TREND
SELECT TO_CHAR(ORDER_DATE, 'MM-YYYY')AS MONTHLY_SALES,SUM(AMOUNT)AS MONTHLY_SALES,COUNT(ORDER_DATE)AS MONTHLY_ORDERS
FROM amazon_sales_report
GROUP BY TO_CHAR(ORDER_DATE, 'MM-YYYY')
ORDER BY TO_CHAR(ORDER_DATE, 'MM-YYYY');

--ORDERS BY SHIPPING CITY
SELECT SHIP_CITY,COUNT(ORDER_DATE)AS TOTAL_ORDERS_SHIPPINGS FROM amazon_sales_report
GROUP BY SHIP_CITY;

--ORDER BY SHIPPING STATE
SELECT SHIP_STATE,COUNT(ORDER_DATE)AS TOTAL_ORDERS_SHIPPING FROM amazon_sales_report
GROUP BY SHIP_STATE
ORDER BY SHIP_STATE;

--CITY AND STATE WISE TOTAL REVENUE
SELECT SHIP_STATE,SUM(AMOUNT)AS TOTAL_AMOUNT_PER_STATE,COUNT(ORDER_DATE)AS TOTAL_ORDERS
FROM amazon_sales_report
GROUP BY SHIP_STATE
ORDER BY SHIP_STATE;

--TOP 10 HIGH COST PRODUCTS BUYER'S
SELECT ORDER_ID,HIGH_COST_PRODUCT_BUYER
FROM(SELECT ORDER_ID,AMOUNT AS HIGH_COST_PRODUCT_BUYER FROM amazon_sales_report
ORDER BY AMOUNT DESC)
WHERE ROWNUM < 11;

--CATEGORY VS QUANTITY SOLD
SELECT CATEGOR,COUNT(CATEGOR)AS NO_OF_CATEGORY, SUM(AMOUNT)AS TOTAL_AMOUNT  FROM amazon_sales_report
GROUP BY CATEGOR;

--CHECKING IF ANY NEGATIVE QUANTITES EXISTS
SELECT QTY FROM amazon_sales_report WHERE QTY <0;

--MOST FREQUENT SIZE ORDERED
SELECT SIZE_,COUNT(SIZE_)AS NO_ORDERS FROM amazon_sales_report
GROUP BY SIZE_
ORDER BY NO_ORDERS DESC;

--TOP 5 BEST PERFORMING DATES
SELECT ORDER_DATE,BEST_PERFORMING_DATES FROM(SELECT ORDER_DATE,COUNT(ORDER_DATE)AS BEST_PERFORMING_DATES FROM amazon_sales_report
GROUP BY ORDER_DATE
ORDER BY BEST_PERFORMING_DATES DESC)
WHERE ROWNUM <6;

--ORDER COST GREATER THAN AVERAGE AMOUNT OF TOTAL SALES
SELECT AMOUNT,COUNT(AMOUNT) FROM amazon_sales_report WHERE 
AMOUNT > (SELECT AVG(AMOUNT)AS AVERAGE_AMOUNT FROM amazon_sales_report)
GROUP BY AMOUNT;

--CANCELLED ORDERS
SELECT STATUS,AMOUNT FROM amazon_sales_report WHERE STATUS LIKE '%C%' AND AMOUNT > 0;

--TOTAL AMOUNT THROUGH CANCELLED
SELECT STATUS,SUM(AMOUNT) AS AMOUNT_CANCELLED FROM amazon_sales_report
WHERE STATUS LIKE '%C%' AND AMOUNT > 0
GROUP BY STATUS;

--RECIEVED AMOUNT FROM CUSTOMERS AFTER DELIVERY
SELECT DISTINCT STATUS,SUM(AMOUNT) FROM amazon_sales_report WHERE STATUS LIKE '%Shipped - Delivered to Buyer%'
GROUP BY STATUS;









